name: Trigger auto deployment for container-app-q46mxco6lngti

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-q46mxco6lngti-AutoDeployTrigger-ff63faef-306e-4cb5-bb59-e97cfcc7aff8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPQ46MXCO6LNGTI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPQ46MXCO6LNGTI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPQ46MXCO6LNGTI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPQ46MXCO6LNGTI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPQ46MXCO6LNGTI_REGISTRY_PASSWORD }}
          containerAppName: container-app-q46mxco6lngti
          resourceGroup: todotemplate6b722
          imageToBuild: default/container-app-q46mxco6lngti:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


